def _clamp_reward(val: float) -> float:
    """Clamp reward to strict (0, 1) range. Never returns 0.0 or 1.0."""
    return max(0.01, min(0.99, float(val)))


def compute_step_reward(action_type: str, state_history: list, is_invalid: bool = False) -> float:
    """
    Computes a dense reward for each step.
    Dense rewards encourage exploration of key features and penalize 
    random guessing or repeating identical actions.
    All returns are clamped to strict (0, 1).
    """
    if is_invalid:
        return _clamp_reward(0.02)  # Low but valid

    # Check for repetition
    previous_actions = [h.get("action_type") for h in state_history]
    if action_type in previous_actions:
        return _clamp_reward(0.03)  # Slightly penalized but still valid
        
    reward = 0.05  # Base reward for any valid non-repeated action
    
    # Meaningful analysis actions yield small bonuses
    valuable_actions = {
        "inspect_catalog_summary": 0.07,
        "inspect_top_tracks": 0.07,
        "inspect_platform_mix": 0.07,
        "inspect_territory_mix": 0.07,
        "inspect_monthly_revenue_trend": 0.08,
        "inspect_anomalies": 0.10,
        "compute_normalized_ttm": 0.10,
    }
    
    reward = valuable_actions.get(action_type, reward)
    
    return _clamp_reward(reward)


def compute_final_reward(submission: dict, ground_truth: dict, steps_taken: int, max_steps: int) -> float:
    """
    Computes the final episode reward based on accuracy of the submission.
    Total episode returning score is generated by Grader, but this acts as the RL terminal reward.
    All returns are clamped to strict (0, 1).
    """
    from .graders import grade_submission
    score = grade_submission(submission, ground_truth, steps_taken, max_steps)
    return _clamp_reward(score)
