def compute_step_reward(action_type: str, state_history: list, is_invalid: bool = False) -> float:
    """
    Computes a dense reward for each step.
    Dense rewards encourage exploration of key features and penalize 
    random guessing or repeating identical actions.
    """
    if is_invalid:
        return -0.02

    # Check for repetition
    previous_actions = [h.get("action_type") for h in state_history]
    if action_type in previous_actions:
        return -0.01  # Penalty for repeating the same action blindly
        
    reward = 0.0
    
    # Meaningful analysis actions yield small rewards
    valuable_actions = {
        "inspect_catalog_summary": 0.02,
        "inspect_top_tracks": 0.02,
        "inspect_platform_mix": 0.02,
        "inspect_territory_mix": 0.02,
        "inspect_monthly_revenue_trend": 0.03,
        "inspect_anomalies": 0.05,
        "compute_normalized_ttm": 0.05,
    }
    
    reward += valuable_actions.get(action_type, 0.0)
    
    # Cap single step dense reward arbitrarily to keep total in bounds
    return max(-0.05, min(0.10, reward))

def compute_final_reward(submission: dict, ground_truth: dict, steps_taken: int, max_steps: int) -> float:
    """
    Computes the final episode reward based on accuracy of the submission.
    Total episode returning score is generated by Grader, but this acts as the RL terminal reward.
    """
    # Uses the grader logic underneath for terminal reward
    from .graders import grade_submission
    score = grade_submission(submission, ground_truth, steps_taken, max_steps)
    return score
